version: "3.4"

services:
    watchtower:
        image: containrrr/watchtower:armhf-latest
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/home/.registry_cred/config.json:/config.json"
        command: "--interval 600"   
        restart: on-failure
    frictionless_scanner:
        image: index.docker.io/meontechno/frictionless-scanner:arm-latest
        command: "python3 qr_scanner/app.py"
        environment:
            BROKER: "broker.hivemq.com"
            ASSOCIATE_CUS_TOPIC: "frictionless/customer-id-scan"
            CART_TOPIC: "REDUNDANT/frictionless/edge-cart"
            SCANNED_CART_API: "https://dev.digitkart.ai/api/frictionless/api/kc/AddToCart"
            WS_URL: "ws://ec2-3-218-19-179.compute-1.amazonaws.com/live-cart"
            ADD_ITEMS_LOCAL_CART: "https://dev.digitkart.ai/api/frictionless/api/kc/updateTransaction"
        env_file:
            - fedge-variables.env
        devices:
            - "/dev/hidraw0:/dev/hidraw1"
        restart: on-failure
    frictionless_edge:
        image : index.docker.io/meontechno/frictionless:arm-latest
        command: bash -c "export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/tegra/libnvbuf_utils.so && python3 image_recognition/app.py"
        network_mode: "host"
        environment:
            PROD_MODEL_URL: "https://bitbucket.org/nsanjay/frictionless_weights/raw/65b6327a3a5d527cbd23bc5f54934c5b9343bd43/vontier/latest.pt"
            OBJ_MODEL_URL: "https://bitbucket.org/nsanjay/frictionless_weights/raw/ad09dec9a785b10bc79f8de52fdfb69dbdbdddd2/object/v1.pt"
            CART_WS_URL: "ws://ec2-3-218-19-179.compute-1.amazonaws.com/lab/live-cart"
            THRESH: 0.8
            SSIM_THRESH: 0.90
            BROKER: "broker.hivemq.com"
            TOPIC1: "frictionless/customer-id-scan"
            TOPIC2: "frictionless/close-transaction"
            TOPIC3: "frictionless/ivlab/start-transaction"
            GRID_PTS: '["83", "144", "546", "462", "118", "187", "490", "475", "138", "147", "497", "475"]'
            CART_TOPIC: "KCED90044/frictionless/edge-cart"
            IMG_WS_URL: "ws://ec2-3-218-19-179.compute-1.amazonaws.com/lab/image-ws"
            CART_API: "https://dev.digitkart.ai/api/frictionless/api/kc/updateTransaction"
            ASSOCIATE_CUST_API: "https://dev.digitkart.ai/api/frictionless/api/kc/associateCustomerId"
        env_file:
            - fedge-variables.env
        volumes:
            - "/home/setup/items_mapping.py:/app/image_recognition/utils/items_mapping.py"
        devices:
            - "/dev/video0:/dev/video0"
            - "/dev/video2:/dev/video1"
            - "/dev/video4:/dev/video2"
        runtime: "nvidia"
        restart: on-failure
